### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [2]:
import numpy as np

In [ ]:
def is_prime(x):
    for i in range(2, x - 1):
        if x % i == 0:
            return False
    return True
 
#1
primi = np.array([i for i in range(2,20) if is_prime(i)])
primi
#2
primi[primi>10]
#3
primi[primi%2==0]

array([False, False, False, False,  True,  True,  True,  True])

### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [ ]:
a = np.arange(20).reshape((4, 5))
print("a",a)
b = a[[1, 3]]
print("b",b)
c = a[3,]
print("c",c)
a/c
 

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [ ]:
arr = np.random.rand(10, 3)
#print(arr) debug
distanze = np.abs(arr - 0.5)
indici_col = np.argmin(distanze, axis=1)
risultato = arr[np.arange(arr.shape[0]), indici_col]
#print(risultato) debug


[[0.96993835 0.72053053 0.37808363]
 [0.43322502 0.75650044 0.48900955]
 [0.94523724 0.7597039  0.96296526]
 [0.35246006 0.65802207 0.05653483]
 [0.18601301 0.31439488 0.44528051]
 [0.96797985 0.27175654 0.17373103]
 [0.61593065 0.79402404 0.81526605]
 [0.06375827 0.81197422 0.00099114]
 [0.20735498 0.13541879 0.32501302]
 [0.11962302 0.3009524  0.14024996]]
[0.37808363 0.48900955 0.7597039  0.35246006 0.44528051 0.27175654
 0.61593065 0.81197422 0.32501302 0.3009524 ]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [ ]:
hr = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 
               162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
#2
print("minima:", np.min(hr)) 
#3
print("massima:", np.max(hr))
#4 
sopra_120 = hr > 120
print(sopra_120)
#5
print(f"in esercizio: {round(np.mean(sopra_120)*100,2)}%")


minima: 60
massima: 164
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
in esercizio: 52.38%


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [17]:
#1
stipendi = np.array([50000, 105250, 55000, 89000])
costo_totale = sum(stipendi)
print("Costo totale:",costo_totale)

# 2
stipendi[1] *= 1.15
print("aumento CEO:",stipendi)

#3
#non è presente perchè il tipo del vettore degli stipendi è int mentre quello che stiamo cercando è float

#4
stipendi = np.array([50000, 105250, 55000, 89000], dtype=float)
stipendi[stipendi == 105250] *= 1.15
print("aumento in decimali CEO:", stipendi)

#5
stipendi[stipendi == np.min(stipendi)] *= 1.20
print("aumento stipendio minimo",stipendi)

#6
stipendi[(stipendi != np.max(stipendi)) & (stipendi != np.min(stipendi))] *= 1.10
print(" aumento stipednio restanti :", stipendi)

#7
print("costo iniziale",costo_totale)
costo_finale = sum(stipendi)
print("costo finale",costo_finale)
print("aumento totale",round(costo_finale-costo_totale))



Costo totale: 299250
aumento CEO: [ 50000 121037  55000  89000]
aumento in decimali CEO: [ 50000.  121037.5  55000.   89000. ]
aumento stipendio minimo [ 60000.  121037.5  55000.   89000. ]
 aumento stipednio restanti : [ 66000.  121037.5  55000.   97900. ]
costo iniziale 299250
costo finale 339937.5
aumento totale 40688


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [ ]:
#1
co2 = np.loadtxt("emissioni.txt")
print(arr)

#2
sopra_soglia = co2[co2>18]
print("sopra 18:", len(sopra_soglia))
print("media sopra 18:", round(np.mean(sopra_soglia), 2))

#3
frazione = np.sum(sopra_soglia) / np.sum(co2)
print(f"emissioni sopra soglia: {round(frazione,2)}%")

[15.44 13.58  8.35 11.51  4.54  9.53 11.42  9.35  7.16  8.97  5.51 15.94
 10.96  4.39 16.54  9.65 14.06 15.28  9.53 18.64  6.89 10.81  7.44  8.94
 10.63 15.5  15.21  4.53 10.68 14.89 10.86  4.51 17.93 12.28 12.8   8.06
 17.35 15.52  5.18  7.37  4.09 11.13  6.43 12.23 19.59  5.02 16.44  9.04
 12.66 19.84 13.55  5.21 14.54 13.17  7.38  8.14  9.09 10.22  6.23 10.
 12.9  11.17  6.16 14.48 18.78 16.3  10.46 11.65  8.37 11.72 16.72  7.63
  7.85  4.95 13.1   7.29 11.42  4.68 15.07 14.51 15.9   5.57 16.96 19.84
 18.48  8.32  4.89  5.05  7.34 19.16 14.96 17.91  6.67 19.52  7.46  5.02
 15.55 17.39  5.65 13.13 16.49 17.11 10.53 13.24 16.55 19.68  8.56 18.47
  9.57 19.76  8.27 12.01 18.95 13.75 11.02  9.77 10.69  5.72 13.65 17.85
  6.35 12.71 14.75  8.39 12.36 17.79 18.21 14.19  5.73 13.83 18.45  6.98
 18.8  12.96 18.24 11.36 10.11 14.45  8.98 14.73 10.99 13.51  7.14 15.87
 10.6  13.59 17.93  9.97  5.71 13.19 11.7   7.62 16.02  7.3   9.77  4.35
 16.81 12.54  5.48 19.5   6.72 12.5  14.03 18.66  7.1

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [27]:
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

#1
maschera = survey_matrix[:, 2] >= 12
filtrati = survey_matrix[maschera]
print(filtrati)

#2
redditi = survey_matrix[survey_matrix[:, 2] >= 12,1]
print(redditi)

#3
print(round(np.mean(redditi),2)) 


[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
[52000 63000 58000]
57666.67


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [33]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])


ages = ages[ages != 999]
print (np.max(ages))

112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [34]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

estratte = np.random.choice(lista_parole, size=5, replace=True)
print("Parole estratte:", estratte)

storia = (
    f"In epoche passate, viveva una donna saggia che era molto orgogliosa "
    f"dell'antico {estratte[0]} che proteggeva. Quando un anziano del villaggio "
    f"venne a chiederle consiglio su come garantire al meglio un raccolto abbondante "
    f"e le offrì il {estratte[1]} come dono, i suoi occhi si spalancarono e lei "
    f'esclamò una sola parola, "{estratte[2]}".\n'
    f"Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, "
    f"gli abitanti cercarono nella foresta un {estratte[3]}.\n"
    f"Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano "
    f"cercando e tutti corsero dalla donna saggia per donarglielo.\n"
    f'Con un sorriso da un orecchio all\'altro, e cantando canti di festa, '
    f'la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo '
    f'del banchetto - nessuno rimarrà mai più senza {estratte[4]}!" '
    f"Ci fu grande gioia e celebrazione."
)

print(storia)

Parole estratte: ['PALLONCINO' 'ALFABETIZZAZIONE' 'PARENTE' 'DIFFERENZA' 'VOLONTARIO']
In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico PALLONCINO che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il ALFABETIZZAZIONE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PARENTE".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un DIFFERENZA.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all'altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza VOLONTARIO!" Ci fu grande gioia e celebrazione.


Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."